<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>flask.app.Flask.handle_exception</title>
    <meta http-equiv="X-UA-Compatible" content="IE=emulateIE7" />
<!--    <link rel="icon" sizes="32x32" href="favicon_32.png">-->
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>&#128270;</text></svg>">
    <link rel="stylesheet" href="highlight.css" type="text/css">
</head>
<body class="pyfile">
<div id="source">
    <div class="highlight">
        <div id="header">
            <div class="content">
                <h1>Method: flask.app.Flask.handle_exception</h1>
                <span>Calls: 35, </span>
                <span>Exceptions: 0, </span>
                <span>Paths: 5</span>
                <br><a href="index.html">Back</a>
            </div>
        </div>
            <p><b>Path 1</b>: 15 calls (0.43)</p>
                <p><button class="input"><span>&#8594;</span> e</button> TypeError (5) BadRequestKeyError (2) ZeroDivisionError (2) ValueError (1) BadRequest (1) NotFound (1) DebugFilesKeyError (1) FormDataRoutingRedirect (...</p>
            <button class="run" title="lines run...">8 run</button>
            <button class="not_run" title="lines not run...">7 not run</button>
            <pre>
<span class="num"><a href="#1">1</a></span><span><span class="k">def</span> <span class="nf">handle_exception</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">Exception</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Response</span><span class="p">:</span></span>
<span class="num"><a href="#2">2</a></span><span><span class="w">        </span><span class="sd">&quot;&quot;&quot;Handle an exception that did not have an error handler</span></span>
<span class="num"><a href="#3">3</a></span><span><span class="sd">        associated with it, or that was raised from an error handler.</span></span>
<span class="num"><a href="#4">4</a></span><span><span class="sd">        This always causes a 500 ``InternalServerError``.</span></span>
<span class="num"><a href="#5">5</a></span><span></span>
<span class="num"><a href="#6">6</a></span><span><span class="sd">        Always sends the :data:`got_request_exception` signal.</span></span>
<span class="num"><a href="#7">7</a></span><span></span>
<span class="num"><a href="#8">8</a></span><span><span class="sd">        If :data:`PROPAGATE_EXCEPTIONS` is ``True``, such as in debug</span></span>
<span class="num"><a href="#9">9</a></span><span><span class="sd">        mode, the error will be re-raised so that the debugger can</span></span>
<span class="num"><a href="#10">10</a></span><span><span class="sd">        display it. Otherwise, the original exception is logged, and</span></span>
<span class="num"><a href="#11">11</a></span><span><span class="sd">        an :exc:`~werkzeug.exceptions.InternalServerError` is returned.</span></span>
<span class="num"><a href="#12">12</a></span><span></span>
<span class="num"><a href="#13">13</a></span><span><span class="sd">        If an error handler is registered for ``InternalServerError`` or</span></span>
<span class="num"><a href="#14">14</a></span><span><span class="sd">        ``500``, it will be used. For consistency, the handler will</span></span>
<span class="num"><a href="#15">15</a></span><span><span class="sd">        always receive the ``InternalServerError``. The original</span></span>
<span class="num"><a href="#16">16</a></span><span><span class="sd">        unhandled exception is available as ``e.original_exception``.</span></span>
<span class="num"><a href="#17">17</a></span><span></span>
<span class="num"><a href="#18">18</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#19">19</a></span><span><span class="sd">            Always passes the ``InternalServerError`` instance to the</span></span>
<span class="num"><a href="#20">20</a></span><span><span class="sd">            handler, setting ``original_exception`` to the unhandled</span></span>
<span class="num"><a href="#21">21</a></span><span><span class="sd">            error.</span></span>
<span class="num"><a href="#22">22</a></span><span></span>
<span class="num"><a href="#23">23</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#24">24</a></span><span><span class="sd">            ``after_request`` functions and other finalization is done</span></span>
<span class="num"><a href="#25">25</a></span><span><span class="sd">            even for the default 500 response when there is no handler.</span></span>
<span class="num"><a href="#26">26</a></span><span></span>
<span class="num"><a href="#27">27</a></span><span><span class="sd">        .. versionadded:: 0.3</span></span>
<span class="num"><a href="#28">28</a></span><span><span class="sd">        &quot;&quot;&quot;</span></span>
<span class="num"><a href="#29">29</a></span><span class="full run">        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span></span>
<span class="num"><a href="#30">30</a></span><span class="full run">        <span class="n">got_request_exception</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">_async_wrapper</span><span class="o">=</span><span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">,</span> <span class="n">exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#31">31</a></span><span class="full run">        <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">config</span><span class="p">[</span><span class="s2">&quot;PROPAGATE_EXCEPTIONS&quot;</span><span class="p">]</span></span>
<span class="num"><a href="#32">32</a></span><span></span>
<span class="num"><a href="#33">33</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#34">34</a></span><span class="full run">            <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">testing</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">debug</span></span>
<span class="num"><a href="#35">35</a></span><span></span>
<span class="num"><a href="#36">36</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span><span class="p">:</span></span>
<span class="num"><a href="#37">37</a></span><span>            <span class="c1"># Re-raise if called with an active exception, otherwise</span></span>
<span class="num"><a href="#38">38</a></span><span>            <span class="c1"># raise the passed in exception.</span></span>
<span class="num"><a href="#39">39</a></span><span class="full run">            <span class="k">if</span> <span class="n">exc_info</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="ow">is</span> <span class="n">e</span><span class="p">:</span></span>
<span class="num"><a href="#40">40</a></span><span class="full run">                <span class="k">raise</span></span>
<span class="num"><a href="#41">41</a></span><span></span>
<span class="num"><a href="#42">42</a></span><span class="full not_run">            <span class="k">raise</span> <span class="n">e</span></span>
<span class="num"><a href="#43">43</a></span><span></span>
<span class="num"><a href="#44">44</a></span><span class="full not_run">        <span class="bp">self</span><span class="o">.</span><span class="n">log_exception</span><span class="p">(</span><span class="n">exc_info</span><span class="p">)</span></span>
<span class="num"><a href="#45">45</a></span><span>        <span class="n">server_error</span><span class="p">:</span> <span class="n">InternalServerError</span> <span class="o">|</span> <span class="n">ft</span><span class="o">.</span><span class="n">ResponseReturnValue</span></span>
<span class="num"><a href="#46">46</a></span><span class="full not_run">        <span class="n">server_error</span> <span class="o">=</span> <span class="n">InternalServerError</span><span class="p">(</span><span class="n">original_exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#47">47</a></span><span class="full not_run">        <span class="n">handler</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_find_error_handler</span><span class="p">(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#48">48</a></span><span></span>
<span class="num"><a href="#49">49</a></span><span class="full not_run">        <span class="k">if</span> <span class="n">handler</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#50">50</a></span><span class="full not_run">            <span class="n">server_error</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">(</span><span class="n">handler</span><span class="p">)(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#51">51</a></span><span></span>
<span class="num"><a href="#52">52</a></span><span class="full not_run">        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">finalize_request</span><span class="p">(</span><span class="n">server_error</span><span class="p">,</span> <span class="n">from_error_handler</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span></span>
            </pre>
            <p><b>Path 2</b>: 8 calls (0.23)</p>
                <p><button class="input"><span>&#8594;</span> e</button> ZeroDivisionError (5) Exception (2) test_session_error_pops_context.<locals>.SessionError (1) </p>
                <p><button class="output"><span>&#8617; return</span></button> Response (8) </p>
            <button class="run" title="lines run...">11 run</button>
            <button class="not_run" title="lines not run...">4 not run</button>
            <pre>
<span class="num"><a href="#1">1</a></span><span><span class="k">def</span> <span class="nf">handle_exception</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">Exception</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Response</span><span class="p">:</span></span>
<span class="num"><a href="#2">2</a></span><span><span class="w">        </span><span class="sd">&quot;&quot;&quot;Handle an exception that did not have an error handler</span></span>
<span class="num"><a href="#3">3</a></span><span><span class="sd">        associated with it, or that was raised from an error handler.</span></span>
<span class="num"><a href="#4">4</a></span><span><span class="sd">        This always causes a 500 ``InternalServerError``.</span></span>
<span class="num"><a href="#5">5</a></span><span></span>
<span class="num"><a href="#6">6</a></span><span><span class="sd">        Always sends the :data:`got_request_exception` signal.</span></span>
<span class="num"><a href="#7">7</a></span><span></span>
<span class="num"><a href="#8">8</a></span><span><span class="sd">        If :data:`PROPAGATE_EXCEPTIONS` is ``True``, such as in debug</span></span>
<span class="num"><a href="#9">9</a></span><span><span class="sd">        mode, the error will be re-raised so that the debugger can</span></span>
<span class="num"><a href="#10">10</a></span><span><span class="sd">        display it. Otherwise, the original exception is logged, and</span></span>
<span class="num"><a href="#11">11</a></span><span><span class="sd">        an :exc:`~werkzeug.exceptions.InternalServerError` is returned.</span></span>
<span class="num"><a href="#12">12</a></span><span></span>
<span class="num"><a href="#13">13</a></span><span><span class="sd">        If an error handler is registered for ``InternalServerError`` or</span></span>
<span class="num"><a href="#14">14</a></span><span><span class="sd">        ``500``, it will be used. For consistency, the handler will</span></span>
<span class="num"><a href="#15">15</a></span><span><span class="sd">        always receive the ``InternalServerError``. The original</span></span>
<span class="num"><a href="#16">16</a></span><span><span class="sd">        unhandled exception is available as ``e.original_exception``.</span></span>
<span class="num"><a href="#17">17</a></span><span></span>
<span class="num"><a href="#18">18</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#19">19</a></span><span><span class="sd">            Always passes the ``InternalServerError`` instance to the</span></span>
<span class="num"><a href="#20">20</a></span><span><span class="sd">            handler, setting ``original_exception`` to the unhandled</span></span>
<span class="num"><a href="#21">21</a></span><span><span class="sd">            error.</span></span>
<span class="num"><a href="#22">22</a></span><span></span>
<span class="num"><a href="#23">23</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#24">24</a></span><span><span class="sd">            ``after_request`` functions and other finalization is done</span></span>
<span class="num"><a href="#25">25</a></span><span><span class="sd">            even for the default 500 response when there is no handler.</span></span>
<span class="num"><a href="#26">26</a></span><span></span>
<span class="num"><a href="#27">27</a></span><span><span class="sd">        .. versionadded:: 0.3</span></span>
<span class="num"><a href="#28">28</a></span><span><span class="sd">        &quot;&quot;&quot;</span></span>
<span class="num"><a href="#29">29</a></span><span class="full run">        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span></span>
<span class="num"><a href="#30">30</a></span><span class="full run">        <span class="n">got_request_exception</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">_async_wrapper</span><span class="o">=</span><span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">,</span> <span class="n">exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#31">31</a></span><span class="full run">        <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">config</span><span class="p">[</span><span class="s2">&quot;PROPAGATE_EXCEPTIONS&quot;</span><span class="p">]</span></span>
<span class="num"><a href="#32">32</a></span><span></span>
<span class="num"><a href="#33">33</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#34">34</a></span><span class="full run">            <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">testing</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">debug</span></span>
<span class="num"><a href="#35">35</a></span><span></span>
<span class="num"><a href="#36">36</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span><span class="p">:</span></span>
<span class="num"><a href="#37">37</a></span><span>            <span class="c1"># Re-raise if called with an active exception, otherwise</span></span>
<span class="num"><a href="#38">38</a></span><span>            <span class="c1"># raise the passed in exception.</span></span>
<span class="num"><a href="#39">39</a></span><span class="full not_run">            <span class="k">if</span> <span class="n">exc_info</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="ow">is</span> <span class="n">e</span><span class="p">:</span></span>
<span class="num"><a href="#40">40</a></span><span class="full not_run">                <span class="k">raise</span></span>
<span class="num"><a href="#41">41</a></span><span></span>
<span class="num"><a href="#42">42</a></span><span class="full not_run">            <span class="k">raise</span> <span class="n">e</span></span>
<span class="num"><a href="#43">43</a></span><span></span>
<span class="num"><a href="#44">44</a></span><span class="full run">        <span class="bp">self</span><span class="o">.</span><span class="n">log_exception</span><span class="p">(</span><span class="n">exc_info</span><span class="p">)</span></span>
<span class="num"><a href="#45">45</a></span><span>        <span class="n">server_error</span><span class="p">:</span> <span class="n">InternalServerError</span> <span class="o">|</span> <span class="n">ft</span><span class="o">.</span><span class="n">ResponseReturnValue</span></span>
<span class="num"><a href="#46">46</a></span><span class="full run">        <span class="n">server_error</span> <span class="o">=</span> <span class="n">InternalServerError</span><span class="p">(</span><span class="n">original_exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#47">47</a></span><span class="full run">        <span class="n">handler</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_find_error_handler</span><span class="p">(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#48">48</a></span><span></span>
<span class="num"><a href="#49">49</a></span><span class="full run">        <span class="k">if</span> <span class="n">handler</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#50">50</a></span><span class="full not_run">            <span class="n">server_error</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">(</span><span class="n">handler</span><span class="p">)(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#51">51</a></span><span></span>
<span class="num"><a href="#52">52</a></span><span class="full run">        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">finalize_request</span><span class="p">(</span><span class="n">server_error</span><span class="p">,</span> <span class="n">from_error_handler</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span></span>
            </pre>
            <p><b>Path 3</b>: 5 calls (0.14)</p>
                <p><button class="input"><span>&#8594;</span> e</button> ZeroDivisionError (4) KeyError (1) </p>
                <p><button class="output"><span>&#8617; return</span></button> Response (5) </p>
            <button class="run" title="lines run...">12 run</button>
            <button class="not_run" title="lines not run...">3 not run</button>
            <pre>
<span class="num"><a href="#1">1</a></span><span><span class="k">def</span> <span class="nf">handle_exception</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">Exception</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Response</span><span class="p">:</span></span>
<span class="num"><a href="#2">2</a></span><span><span class="w">        </span><span class="sd">&quot;&quot;&quot;Handle an exception that did not have an error handler</span></span>
<span class="num"><a href="#3">3</a></span><span><span class="sd">        associated with it, or that was raised from an error handler.</span></span>
<span class="num"><a href="#4">4</a></span><span><span class="sd">        This always causes a 500 ``InternalServerError``.</span></span>
<span class="num"><a href="#5">5</a></span><span></span>
<span class="num"><a href="#6">6</a></span><span><span class="sd">        Always sends the :data:`got_request_exception` signal.</span></span>
<span class="num"><a href="#7">7</a></span><span></span>
<span class="num"><a href="#8">8</a></span><span><span class="sd">        If :data:`PROPAGATE_EXCEPTIONS` is ``True``, such as in debug</span></span>
<span class="num"><a href="#9">9</a></span><span><span class="sd">        mode, the error will be re-raised so that the debugger can</span></span>
<span class="num"><a href="#10">10</a></span><span><span class="sd">        display it. Otherwise, the original exception is logged, and</span></span>
<span class="num"><a href="#11">11</a></span><span><span class="sd">        an :exc:`~werkzeug.exceptions.InternalServerError` is returned.</span></span>
<span class="num"><a href="#12">12</a></span><span></span>
<span class="num"><a href="#13">13</a></span><span><span class="sd">        If an error handler is registered for ``InternalServerError`` or</span></span>
<span class="num"><a href="#14">14</a></span><span><span class="sd">        ``500``, it will be used. For consistency, the handler will</span></span>
<span class="num"><a href="#15">15</a></span><span><span class="sd">        always receive the ``InternalServerError``. The original</span></span>
<span class="num"><a href="#16">16</a></span><span><span class="sd">        unhandled exception is available as ``e.original_exception``.</span></span>
<span class="num"><a href="#17">17</a></span><span></span>
<span class="num"><a href="#18">18</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#19">19</a></span><span><span class="sd">            Always passes the ``InternalServerError`` instance to the</span></span>
<span class="num"><a href="#20">20</a></span><span><span class="sd">            handler, setting ``original_exception`` to the unhandled</span></span>
<span class="num"><a href="#21">21</a></span><span><span class="sd">            error.</span></span>
<span class="num"><a href="#22">22</a></span><span></span>
<span class="num"><a href="#23">23</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#24">24</a></span><span><span class="sd">            ``after_request`` functions and other finalization is done</span></span>
<span class="num"><a href="#25">25</a></span><span><span class="sd">            even for the default 500 response when there is no handler.</span></span>
<span class="num"><a href="#26">26</a></span><span></span>
<span class="num"><a href="#27">27</a></span><span><span class="sd">        .. versionadded:: 0.3</span></span>
<span class="num"><a href="#28">28</a></span><span><span class="sd">        &quot;&quot;&quot;</span></span>
<span class="num"><a href="#29">29</a></span><span class="full run">        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span></span>
<span class="num"><a href="#30">30</a></span><span class="full run">        <span class="n">got_request_exception</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">_async_wrapper</span><span class="o">=</span><span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">,</span> <span class="n">exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#31">31</a></span><span class="full run">        <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">config</span><span class="p">[</span><span class="s2">&quot;PROPAGATE_EXCEPTIONS&quot;</span><span class="p">]</span></span>
<span class="num"><a href="#32">32</a></span><span></span>
<span class="num"><a href="#33">33</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#34">34</a></span><span class="full run">            <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">testing</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">debug</span></span>
<span class="num"><a href="#35">35</a></span><span></span>
<span class="num"><a href="#36">36</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span><span class="p">:</span></span>
<span class="num"><a href="#37">37</a></span><span>            <span class="c1"># Re-raise if called with an active exception, otherwise</span></span>
<span class="num"><a href="#38">38</a></span><span>            <span class="c1"># raise the passed in exception.</span></span>
<span class="num"><a href="#39">39</a></span><span class="full not_run">            <span class="k">if</span> <span class="n">exc_info</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="ow">is</span> <span class="n">e</span><span class="p">:</span></span>
<span class="num"><a href="#40">40</a></span><span class="full not_run">                <span class="k">raise</span></span>
<span class="num"><a href="#41">41</a></span><span></span>
<span class="num"><a href="#42">42</a></span><span class="full not_run">            <span class="k">raise</span> <span class="n">e</span></span>
<span class="num"><a href="#43">43</a></span><span></span>
<span class="num"><a href="#44">44</a></span><span class="full run">        <span class="bp">self</span><span class="o">.</span><span class="n">log_exception</span><span class="p">(</span><span class="n">exc_info</span><span class="p">)</span></span>
<span class="num"><a href="#45">45</a></span><span>        <span class="n">server_error</span><span class="p">:</span> <span class="n">InternalServerError</span> <span class="o">|</span> <span class="n">ft</span><span class="o">.</span><span class="n">ResponseReturnValue</span></span>
<span class="num"><a href="#46">46</a></span><span class="full run">        <span class="n">server_error</span> <span class="o">=</span> <span class="n">InternalServerError</span><span class="p">(</span><span class="n">original_exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#47">47</a></span><span class="full run">        <span class="n">handler</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_find_error_handler</span><span class="p">(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#48">48</a></span><span></span>
<span class="num"><a href="#49">49</a></span><span class="full run">        <span class="k">if</span> <span class="n">handler</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#50">50</a></span><span class="full run">            <span class="n">server_error</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">(</span><span class="n">handler</span><span class="p">)(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#51">51</a></span><span></span>
<span class="num"><a href="#52">52</a></span><span class="full run">        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">finalize_request</span><span class="p">(</span><span class="n">server_error</span><span class="p">,</span> <span class="n">from_error_handler</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span></span>
            </pre>
            <p><b>Path 4</b>: 5 calls (0.14)</p>
                <p><button class="input"><span>&#8594;</span> e</button> KeyError (3) TestGenericHandlers.Custom (2) </p>
                <p><button class="output"><span>&#8617; return</span></button> Response (5) </p>
            <button class="run" title="lines run...">11 run</button>
            <button class="not_run" title="lines not run...">4 not run</button>
            <pre>
<span class="num"><a href="#1">1</a></span><span><span class="k">def</span> <span class="nf">handle_exception</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">Exception</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Response</span><span class="p">:</span></span>
<span class="num"><a href="#2">2</a></span><span><span class="w">        </span><span class="sd">&quot;&quot;&quot;Handle an exception that did not have an error handler</span></span>
<span class="num"><a href="#3">3</a></span><span><span class="sd">        associated with it, or that was raised from an error handler.</span></span>
<span class="num"><a href="#4">4</a></span><span><span class="sd">        This always causes a 500 ``InternalServerError``.</span></span>
<span class="num"><a href="#5">5</a></span><span></span>
<span class="num"><a href="#6">6</a></span><span><span class="sd">        Always sends the :data:`got_request_exception` signal.</span></span>
<span class="num"><a href="#7">7</a></span><span></span>
<span class="num"><a href="#8">8</a></span><span><span class="sd">        If :data:`PROPAGATE_EXCEPTIONS` is ``True``, such as in debug</span></span>
<span class="num"><a href="#9">9</a></span><span><span class="sd">        mode, the error will be re-raised so that the debugger can</span></span>
<span class="num"><a href="#10">10</a></span><span><span class="sd">        display it. Otherwise, the original exception is logged, and</span></span>
<span class="num"><a href="#11">11</a></span><span><span class="sd">        an :exc:`~werkzeug.exceptions.InternalServerError` is returned.</span></span>
<span class="num"><a href="#12">12</a></span><span></span>
<span class="num"><a href="#13">13</a></span><span><span class="sd">        If an error handler is registered for ``InternalServerError`` or</span></span>
<span class="num"><a href="#14">14</a></span><span><span class="sd">        ``500``, it will be used. For consistency, the handler will</span></span>
<span class="num"><a href="#15">15</a></span><span><span class="sd">        always receive the ``InternalServerError``. The original</span></span>
<span class="num"><a href="#16">16</a></span><span><span class="sd">        unhandled exception is available as ``e.original_exception``.</span></span>
<span class="num"><a href="#17">17</a></span><span></span>
<span class="num"><a href="#18">18</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#19">19</a></span><span><span class="sd">            Always passes the ``InternalServerError`` instance to the</span></span>
<span class="num"><a href="#20">20</a></span><span><span class="sd">            handler, setting ``original_exception`` to the unhandled</span></span>
<span class="num"><a href="#21">21</a></span><span><span class="sd">            error.</span></span>
<span class="num"><a href="#22">22</a></span><span></span>
<span class="num"><a href="#23">23</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#24">24</a></span><span><span class="sd">            ``after_request`` functions and other finalization is done</span></span>
<span class="num"><a href="#25">25</a></span><span><span class="sd">            even for the default 500 response when there is no handler.</span></span>
<span class="num"><a href="#26">26</a></span><span></span>
<span class="num"><a href="#27">27</a></span><span><span class="sd">        .. versionadded:: 0.3</span></span>
<span class="num"><a href="#28">28</a></span><span><span class="sd">        &quot;&quot;&quot;</span></span>
<span class="num"><a href="#29">29</a></span><span class="full run">        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span></span>
<span class="num"><a href="#30">30</a></span><span class="full run">        <span class="n">got_request_exception</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">_async_wrapper</span><span class="o">=</span><span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">,</span> <span class="n">exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#31">31</a></span><span class="full run">        <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">config</span><span class="p">[</span><span class="s2">&quot;PROPAGATE_EXCEPTIONS&quot;</span><span class="p">]</span></span>
<span class="num"><a href="#32">32</a></span><span></span>
<span class="num"><a href="#33">33</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#34">34</a></span><span class="full not_run">            <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">testing</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">debug</span></span>
<span class="num"><a href="#35">35</a></span><span></span>
<span class="num"><a href="#36">36</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span><span class="p">:</span></span>
<span class="num"><a href="#37">37</a></span><span>            <span class="c1"># Re-raise if called with an active exception, otherwise</span></span>
<span class="num"><a href="#38">38</a></span><span>            <span class="c1"># raise the passed in exception.</span></span>
<span class="num"><a href="#39">39</a></span><span class="full not_run">            <span class="k">if</span> <span class="n">exc_info</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="ow">is</span> <span class="n">e</span><span class="p">:</span></span>
<span class="num"><a href="#40">40</a></span><span class="full not_run">                <span class="k">raise</span></span>
<span class="num"><a href="#41">41</a></span><span></span>
<span class="num"><a href="#42">42</a></span><span class="full not_run">            <span class="k">raise</span> <span class="n">e</span></span>
<span class="num"><a href="#43">43</a></span><span></span>
<span class="num"><a href="#44">44</a></span><span class="full run">        <span class="bp">self</span><span class="o">.</span><span class="n">log_exception</span><span class="p">(</span><span class="n">exc_info</span><span class="p">)</span></span>
<span class="num"><a href="#45">45</a></span><span>        <span class="n">server_error</span><span class="p">:</span> <span class="n">InternalServerError</span> <span class="o">|</span> <span class="n">ft</span><span class="o">.</span><span class="n">ResponseReturnValue</span></span>
<span class="num"><a href="#46">46</a></span><span class="full run">        <span class="n">server_error</span> <span class="o">=</span> <span class="n">InternalServerError</span><span class="p">(</span><span class="n">original_exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#47">47</a></span><span class="full run">        <span class="n">handler</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_find_error_handler</span><span class="p">(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#48">48</a></span><span></span>
<span class="num"><a href="#49">49</a></span><span class="full run">        <span class="k">if</span> <span class="n">handler</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#50">50</a></span><span class="full run">            <span class="n">server_error</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">(</span><span class="n">handler</span><span class="p">)(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#51">51</a></span><span></span>
<span class="num"><a href="#52">52</a></span><span class="full run">        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">finalize_request</span><span class="p">(</span><span class="n">server_error</span><span class="p">,</span> <span class="n">from_error_handler</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span></span>
            </pre>
            <p><b>Path 5</b>: 2 calls (0.06)</p>
                <p><button class="input"><span>&#8594;</span> e</button> ValueError (1) ZeroDivisionError (1) </p>
            <button class="run" title="lines run...">7 run</button>
            <button class="not_run" title="lines not run...">8 not run</button>
            <pre>
<span class="num"><a href="#1">1</a></span><span><span class="k">def</span> <span class="nf">handle_exception</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">e</span><span class="p">:</span> <span class="ne">Exception</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="n">Response</span><span class="p">:</span></span>
<span class="num"><a href="#2">2</a></span><span><span class="w">        </span><span class="sd">&quot;&quot;&quot;Handle an exception that did not have an error handler</span></span>
<span class="num"><a href="#3">3</a></span><span><span class="sd">        associated with it, or that was raised from an error handler.</span></span>
<span class="num"><a href="#4">4</a></span><span><span class="sd">        This always causes a 500 ``InternalServerError``.</span></span>
<span class="num"><a href="#5">5</a></span><span></span>
<span class="num"><a href="#6">6</a></span><span><span class="sd">        Always sends the :data:`got_request_exception` signal.</span></span>
<span class="num"><a href="#7">7</a></span><span></span>
<span class="num"><a href="#8">8</a></span><span><span class="sd">        If :data:`PROPAGATE_EXCEPTIONS` is ``True``, such as in debug</span></span>
<span class="num"><a href="#9">9</a></span><span><span class="sd">        mode, the error will be re-raised so that the debugger can</span></span>
<span class="num"><a href="#10">10</a></span><span><span class="sd">        display it. Otherwise, the original exception is logged, and</span></span>
<span class="num"><a href="#11">11</a></span><span><span class="sd">        an :exc:`~werkzeug.exceptions.InternalServerError` is returned.</span></span>
<span class="num"><a href="#12">12</a></span><span></span>
<span class="num"><a href="#13">13</a></span><span><span class="sd">        If an error handler is registered for ``InternalServerError`` or</span></span>
<span class="num"><a href="#14">14</a></span><span><span class="sd">        ``500``, it will be used. For consistency, the handler will</span></span>
<span class="num"><a href="#15">15</a></span><span><span class="sd">        always receive the ``InternalServerError``. The original</span></span>
<span class="num"><a href="#16">16</a></span><span><span class="sd">        unhandled exception is available as ``e.original_exception``.</span></span>
<span class="num"><a href="#17">17</a></span><span></span>
<span class="num"><a href="#18">18</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#19">19</a></span><span><span class="sd">            Always passes the ``InternalServerError`` instance to the</span></span>
<span class="num"><a href="#20">20</a></span><span><span class="sd">            handler, setting ``original_exception`` to the unhandled</span></span>
<span class="num"><a href="#21">21</a></span><span><span class="sd">            error.</span></span>
<span class="num"><a href="#22">22</a></span><span></span>
<span class="num"><a href="#23">23</a></span><span><span class="sd">        .. versionchanged:: 1.1.0</span></span>
<span class="num"><a href="#24">24</a></span><span><span class="sd">            ``after_request`` functions and other finalization is done</span></span>
<span class="num"><a href="#25">25</a></span><span><span class="sd">            even for the default 500 response when there is no handler.</span></span>
<span class="num"><a href="#26">26</a></span><span></span>
<span class="num"><a href="#27">27</a></span><span><span class="sd">        .. versionadded:: 0.3</span></span>
<span class="num"><a href="#28">28</a></span><span><span class="sd">        &quot;&quot;&quot;</span></span>
<span class="num"><a href="#29">29</a></span><span class="full run">        <span class="n">exc_info</span> <span class="o">=</span> <span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">()</span></span>
<span class="num"><a href="#30">30</a></span><span class="full run">        <span class="n">got_request_exception</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">_async_wrapper</span><span class="o">=</span><span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">,</span> <span class="n">exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#31">31</a></span><span class="full run">        <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">config</span><span class="p">[</span><span class="s2">&quot;PROPAGATE_EXCEPTIONS&quot;</span><span class="p">]</span></span>
<span class="num"><a href="#32">32</a></span><span></span>
<span class="num"><a href="#33">33</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span> <span class="ow">is</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#34">34</a></span><span class="full not_run">            <span class="n">propagate</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">testing</span> <span class="ow">or</span> <span class="bp">self</span><span class="o">.</span><span class="n">debug</span></span>
<span class="num"><a href="#35">35</a></span><span></span>
<span class="num"><a href="#36">36</a></span><span class="full run">        <span class="k">if</span> <span class="n">propagate</span><span class="p">:</span></span>
<span class="num"><a href="#37">37</a></span><span>            <span class="c1"># Re-raise if called with an active exception, otherwise</span></span>
<span class="num"><a href="#38">38</a></span><span>            <span class="c1"># raise the passed in exception.</span></span>
<span class="num"><a href="#39">39</a></span><span class="full run">            <span class="k">if</span> <span class="n">exc_info</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span> <span class="ow">is</span> <span class="n">e</span><span class="p">:</span></span>
<span class="num"><a href="#40">40</a></span><span class="full run">                <span class="k">raise</span></span>
<span class="num"><a href="#41">41</a></span><span></span>
<span class="num"><a href="#42">42</a></span><span class="full not_run">            <span class="k">raise</span> <span class="n">e</span></span>
<span class="num"><a href="#43">43</a></span><span></span>
<span class="num"><a href="#44">44</a></span><span class="full not_run">        <span class="bp">self</span><span class="o">.</span><span class="n">log_exception</span><span class="p">(</span><span class="n">exc_info</span><span class="p">)</span></span>
<span class="num"><a href="#45">45</a></span><span>        <span class="n">server_error</span><span class="p">:</span> <span class="n">InternalServerError</span> <span class="o">|</span> <span class="n">ft</span><span class="o">.</span><span class="n">ResponseReturnValue</span></span>
<span class="num"><a href="#46">46</a></span><span class="full not_run">        <span class="n">server_error</span> <span class="o">=</span> <span class="n">InternalServerError</span><span class="p">(</span><span class="n">original_exception</span><span class="o">=</span><span class="n">e</span><span class="p">)</span></span>
<span class="num"><a href="#47">47</a></span><span class="full not_run">        <span class="n">handler</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_find_error_handler</span><span class="p">(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#48">48</a></span><span></span>
<span class="num"><a href="#49">49</a></span><span class="full not_run">        <span class="k">if</span> <span class="n">handler</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span></span>
<span class="num"><a href="#50">50</a></span><span class="full not_run">            <span class="n">server_error</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">ensure_sync</span><span class="p">(</span><span class="n">handler</span><span class="p">)(</span><span class="n">server_error</span><span class="p">)</span></span>
<span class="num"><a href="#51">51</a></span><span></span>
<span class="num"><a href="#52">52</a></span><span class="full not_run">        <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">finalize_request</span><span class="p">(</span><span class="n">server_error</span><span class="p">,</span> <span class="n">from_error_handler</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span></span>
            </pre>
    </div>
</div>
<i class="bi bi-arrow-down"></i>
</body>
</html>
